---
networks:
    - name: "cognet"
      auto: true
      servers:
        - hostname: "irc.tamu.edu"
          port: 6667
        - hostname: "irc.floofy-skirts.org"
          port: 6667
        - hostname: "irc.drwilco.net"
          port: 6667
      nick:
        - "jumptest"
        - "jumptest_"
        - "jumptest~"
      fullname: "Chansey IRC Module"
      channels:
        - "#bottest"
